# Generated by Django 5.1.2 on 2024-10-31 09:09

import carshop.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='VIN')),
                ('color', models.CharField(choices=[('W', 'Белый'), ('G', 'Серебристый'), ('B', 'Черный'), ('Y', 'Желтый'), ('BL', 'Синий'), ('O', 'Другой')], default='O', max_length=2, verbose_name='Цвет')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['vin'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование марки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='carshop_bra_name_eab354_idx')],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=carshop.models.car_directory_path, verbose_name='Фото')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='carshop.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Наименование Модели')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_models', to='carshop.brand', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Наименование Двигателя')),
                ('fuel_type', models.CharField(choices=[('P', 'Бензин'), ('D', 'Дизель'), ('E', 'Электро'), ('H', 'Гибрид')], max_length=1, verbose_name='Тип двигателя')),
                ('volume', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Объем')),
                ('power', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='Мощность двигателя, л.с.')),
                ('milage', models.IntegerField(verbose_name='Пробег')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Двигатель',
                'verbose_name_plural': 'Двигатели',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='carshop_eng_name_840857_idx')],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='carshop.engine', verbose_name='Двигатель'),
        ),
        migrations.CreateModel(
            name='Gen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Наименование Поколения')),
                ('image', models.ImageField(upload_to=carshop.models.gen_directory_path, verbose_name='Фото поколения')),
                ('release_start', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(3000)], verbose_name='Начало выпуска')),
                ('release_end', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(3000)], verbose_name='Окончание выпуска')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gens', to='carshop.carmodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Поколение',
                'verbose_name_plural': 'Поколения',
                'ordering': ['release_start'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='gen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='carshop.gen', verbose_name='Поколение'),
        ),
        migrations.AddIndex(
            model_name='carmodel',
            index=models.Index(fields=['name'], name='carshop_car_name_f12b21_idx'),
        ),
        migrations.AddIndex(
            model_name='gen',
            index=models.Index(fields=['release_start'], name='carshop_gen_release_0187d0_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['vin'], name='carshop_car_vin_132780_idx'),
        ),
    ]
