# Generated by Django 5.1.3 on 2024-11-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshop', '0003_alter_brand_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(max_length=20, verbose_name='URL'),
        ),
    ]
