# Generated by Django 5.1.3 on 2024-11-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshop', '0008_gen_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gen',
            name='slug',
            field=models.SlugField(max_length=60, unique=True),
        ),
    ]
