# Generated by Django 5.1.3 on 2024-11-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshop', '0009_alter_gen_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=40),
        ),
    ]
