# Generated by Django 5.1.3 on 2024-11-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshop', '0010_engine_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='slug',
            field=models.SlugField(max_length=40, unique=True),
        ),
    ]
