# Generated by Django 5.1.3 on 2024-11-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carshop', '0011_alter_engine_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='slug',
        ),
    ]
