# Generated by Django 5.1.3 on 2024-11-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshop', '0012_remove_engine_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=140),
        ),
    ]
