# Generated by Django 5.1.3 on 2024-11-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshop', '0013_car_name_car_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='car',
            name='slug',
            field=models.SlugField(max_length=140, unique=True, verbose_name='URL'),
        ),
    ]
