# Generated by Django 5.1.3 on 2024-11-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshop', '0014_alter_car_name_alter_car_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
