# Generated by Django 5.1.3 on 2024-11-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshop', '0015_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
    ]
