# Generated by Django 5.1.3 on 2024-11-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carshop', '0016_alter_car_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='milage',
        ),
        migrations.AddField(
            model_name='car',
            name='milage',
            field=models.IntegerField(blank=True, default=0, verbose_name='Пробег'),
        ),
    ]
